In [3]:
import numpy as np

In [15]:
#(a) Reverse the NumPy array
arr = np.array([1,2,3,6,4,5])

In [17]:
print("Reversed Array", arr[::-1])

Reversed Array [5 4 6 3 2 1]


In [19]:
#(b) Flatten the NumPy array
arr1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
print("Flattened method1:", arr1.flatten())
print("Flattened method2:", arr1.ravel())

Flattened method1: [1 2 3 2 4 5 1 2 3]
Flattened method2: [1 2 3 2 4 5 1 2 3]


In [25]:
#(c) Compare arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print("Array Comparison:", np.array_equal(arr1,arr2))

Array Comparison: True


In [23]:
#(d) most frequent value and indices 
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
print("mode of x:", np.bincount(x).argmax())
print("Indices in x:", np.where(x == np.bincount(x).argmax()))
print("mode of y:", np.bincount(y).argmax())
print("Indices in y:", np.where(y == np.bincount(y).argmax()))

mode of x: 1
Indices in x: (array([0, 5, 7, 8, 9], dtype=int64),)
mode of y: 1
Indices in y: (array([0, 1, 2], dtype=int64),)


In [27]:
#(e) for matrix
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("sum of elements:", gfg.sum())
print("row-wise sum:", gfg.sum(axis=1))
print("column-wise sum:", gfg.sum(axis=0))

sum of elements: 45
row-wise sum: [[14]
 [16]
 [15]]
column-wise sum: [[20  9 16]]


In [9]:
#(f) matrix operations
n = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("sum of diagonal:", np.trace(n))
eig_vals, eig_vecs = np.linalg.eig(n)
print("eigen values:", eig_vals)
print("eigen vectors:", eig_vecs)
print("inverse:", np.linalg.inv(n))
print("determinant:", np.linalg.det(n))

sum of diagonal: 176
eigen values: [98.16835147 28.097044   49.73460452]
eigen vectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant: 137180.0000000001


In [13]:
#(g) multiply and covariance (i)
p = [[1,2],[2,3]]
q = [[4,5],[6,7]]
print("matrix multiplication:", np.dot(p,q))
print("covariance:", np.cov(p))

matrix multiplication: [[16 19]
 [26 31]]
covariance: [[0.5 0.5]
 [0.5 0.5]]


In [29]:
#(g) multiply and covariance (ii)
p = [[1,2],[2,3],[4,5]]
q = [[4,5,1],[6,7,2]]
print("matrix multiplication:", np.dot(p,q))
print("covariance:", np.cov(p))

matrix multiplication: [[16 19  5]
 [26 31  8]
 [46 55 14]]
covariance: [[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [31]:
#(h) inner, outer and cartesian product 
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
print("inner product:", np.inner(x,y))
print("outer product:", np.outer(x,y))
car=np.array([(a,b) for a in x.flatten() for b in y.flatten()])
print("cartesian product:", car)

inner product: [[17 52]
 [13 62]]
outer product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cartesian product: [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [19]:
# question 2
array = np.array([[1, -2, 3],[-4, 5, -6]])
#a(i)
print("absolute values:",np.abs(array))
flat=array.flatten()
print("flatten percentiles:")

#a(ii)
print("25th:",np.percentile(flat,25))
print("50th:",np.percentile(flat,50))
print("75th:",np.percentile(flat,75))
print("column percentiles:")
print("25th:",np.percentile(array,25,axis=0))
print("50th:",np.percentile(array,50,axis=0))
print("75th:",np.percentile(array,75,axis=0))
print("row percentiles:")
print("25th:",np.percentile(array,25,axis=1))
print("50th:",np.percentile(array,50,axis=1))
print("75th:",np.percentile(array,75,axis=1))

#a(iii)
print("Stats:")
print("mean",np.mean(flat))
print("median:",np.median(flat))
print("standard deviation",np.std(flat))
print("column:")
print("mean",np.mean(array,axis=0))
print("median:",np.median(array,axis=0))
print("standard deviation",np.std(array,axis=0))
print("row:")
print("mean",np.mean(array,axis=1))
print("median:",np.median(array,axis=1))
print("standard deviation",np.std(array,axis=1))

absolute values: [[1 2 3]
 [4 5 6]]
flatten percentiles:
25th: -3.5
50th: -0.5
75th: 2.5
column percentiles:
25th: [-2.75 -0.25 -3.75]
50th: [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]
row percentiles:
25th: [-0.5 -5. ]
50th: [ 1. -4.]
75th: [2.  0.5]
Stats:
mean -0.5
median: -0.5
standard deviation 3.8622100754188224
column:
mean [-1.5  1.5 -1.5]
median: [-1.5  1.5 -1.5]
standard deviation [2.5 3.5 4.5]
row:
mean [ 0.66666667 -1.66666667]
median: [ 1. -4.]
standard deviation [2.05480467 4.78423336]


In [21]:
#question 2b
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("floor",np.floor(a))
print("cieling",np.ceil(a))
print("truncated",np.trunc(a))
print("rounded",np.round(a))

floor [-2. -2. -1.  0.  1.  1.  3.]
cieling [-1. -1. -0.  1.  2.  2.  3.]
truncated [-1. -1. -0.  0.  1.  1.  3.]
rounded [-2. -2. -0.  0.  2.  2.  3.]


In [33]:
#question 3a
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("sorted:",np.sort(array))
print("indices of sorted:",np.argsort(array))
print("4 smallest",np.sort(array)[:4])
print("5 largest",np.sort(array)[-5:])

sorted: [ 10  16  16  52  54  62 453]
indices of sorted: [0 3 4 1 5 2 6]
4 smallest [10 16 16 52]
5 largest [ 16  52  54  62 453]


In [35]:
#question 3b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers=array[np.equal(np.mod(array,1),0)]
print("integers",integers)
floats=array[np.not_equal(np.mod(array,1),0)]
print("floats",floats)

integers [1. 2. 3. 2.]
floats [1.2 2.2]


In [43]:
#question 4a
from PIL import Image
arr = img_to_array(r"C:\Users\keshe\Downloads\images_mlone.jpeg")
def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    #save as text file 
    np.savetxt("image_array.txt", arr.reshape(-1,arr.shape[-1]) if arr.ndim == 3 else arr, fmt="%d")
    return arr

#load the saved file 
loaded = np.loadtxt("image_array.txt", dtype=int)
print("loaded array shape:", loaded.shape)

loaded array shape: (50246, 3)
